apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx-git-cd
  name: nginx-git-cd
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: nginx-git-cd
  type: NodePort
