apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx-git-cd
  name: nginx-git-cd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-git-cd
  template:
    metadata:
      labels:
        app: nginx-git-cd
    spec:
      containers:
      - image: nginx
        name: nginx
